### ISSUE TITLE
Access denied while opening our own Private notebook 

### ISSUE THREAD

**Issue by Prateek032** [att/rcloud#1578]
When we try to load some of our own Private Notebooks, it is showing following error 

![error while opening our own private notebook](https://cloud.githubusercontent.com/assets/10941328/8424500/0ce0eb30-1f19-11e5-83c1-04b50eb0ce7f.PNG)

and following error in session div

![error while opening our own private notebook _2](https://cloud.githubusercontent.com/assets/10941328/8424489/e98b3974-1f18-11e5-846b-9c88a45e4821.PNG)

**Comment by gordonwoodhull** [comment]
Is this when writing on one RCloud server and reading on another? I already filed #1574

**Comment by Prateek032** [comment]
We observed this issue on Local instance

**Comment by gordonwoodhull** [comment]
Wow, okay. Any other clues, was the SKS restarted or anything?

**Comment by Prateek032** [comment]
Nope SKS is not restarted, We just cloned the latest Commit and started SKS

**Comment by s-u** [comment]
Are you using persistent SKS? Note that users can also explicitly reset their key which will make all their old notebook inaccessible by design. Either way, it just says you don't have the key so I don't think this is a bug. You said you didn't re-start SKS but you also say you cloned and started SKS. Make sure you use persistent SKS with a database (that is the default setup as long as the permissions are right) - that is quite important if you want to keep your keys.

**Comment by gordonwoodhull** [comment]
They are talking about an SKS server with default setup here. The clone is just a git clone. 

Perhaps it is permissions trouble. But it doesn't even sound like the server was restarted.

**Comment by s-u** [comment]
Ok, it wasn't clear from the text.

But, that said, I had a similar issue when trying to replicate #1520 -- I could not replicate it, but I got a hash mismatch after uploading few Mbs of files into an encrypted notebook so I wonder if those are related...

**Comment by gordonwoodhull** [comment]
This was resolved by @s-u's advice, and I misunderstood. The SKS was being run from a new directory, thus had a new database.

**Comment by prateek05** [comment]
@s-u same here I can replicate it with the following steps: 
·         Create a new group
·         Assign any notebook to that group
·         Upload any csv file of size around 500 kb and rename it . Session div will show error message:
Error: update_notebook: Error in rcloud.decrypt(ec, key) :
·          Now switch to any other notebook and switch back
It is clearly related to #1520

**Comment by gordonwoodhull** [comment]
@prateek05 I think you mean #1493

**Comment by s-u** [comment]
I can no longer replicate it since the above update.

**Comment by Prateek032** [comment]
This issue still can be replicated with the steps mentioned by @prateek05 
> Create a new group
· Assign any notebook to that group
· Upload any csv file of size around 500 kb and rename it . Session div will show error message:
Error: update_notebook: Error in rcloud.decrypt(ec, key) :
· Now switch to any other notebook and switch back

**Comment by s-u** [comment]
I cannot replicate it after the changes - did you upgrade the github package on the instance you're testing?

**Comment by gordonwoodhull** [comment]
this is rcloud-2 as well, i presume - reopening

**Comment by Prateek032** [comment]
Yes, still it is replicable on RCloud-2

**Comment by gordonwoodhull** [comment]
I can repro. It looks like this is probably the truncation bug, since for a moment the total asset size is greater than 1MB, and they are one asset to GitHub.

**Comment by s-u** [comment]
I guess my file size was just small enough not to trigger it. Please be more specific about the sizes you use (ideally, mention the actual size you tested it with) so we ensure reproducibility.

**Comment by s-u** [comment]
ok, this is direct consequence of #1496

**Comment by s-u** [comment]
Which is now fixed and I can confirm that the renaming of large encrypted assets works. Note that the fix restores access to the notebooks that were previously truncated so they become avaiable.

**Comment by Prateek032** [comment]
This issue is still replicable with the above mentioned steps but, this time it is throwing different error and the error is

![private](https://cloud.githubusercontent.com/assets/10941328/9762650/83885390-5722-11e5-88ce-115660e8ae1f.PNG)

**Comment by s-u** [comment]
caused by #1658
